from app.services.pipeline_state import (
    PIPELINE_STAGE_CLEANUP,
    PIPELINE_STAGE_DIARIZE,
    PIPELINE_STAGE_DOWNLOAD,
    PIPELINE_STAGE_EMBED,
    PIPELINE_STAGE_QUEUED,
    PIPELINE_STAGE_SEQUENCE,
    PIPELINE_STAGE_SUMMARIZE,
    PIPELINE_STAGE_TRANSCRIBE,
)

PIPELINE_QUEUE_AUDIO = "audio"
PIPELINE_QUEUE_DIARIZE = "diarize"
PIPELINE_QUEUE_POST = "post"

PIPELINE_STAGE_QUEUE_MAP = {
    PIPELINE_STAGE_QUEUED: PIPELINE_QUEUE_AUDIO,
    PIPELINE_STAGE_DOWNLOAD: PIPELINE_QUEUE_AUDIO,
    PIPELINE_STAGE_TRANSCRIBE: PIPELINE_QUEUE_AUDIO,
    PIPELINE_STAGE_DIARIZE: PIPELINE_QUEUE_DIARIZE,
    PIPELINE_STAGE_CLEANUP: PIPELINE_QUEUE_POST,
    PIPELINE_STAGE_SUMMARIZE: PIPELINE_QUEUE_POST,
    PIPELINE_STAGE_EMBED: PIPELINE_QUEUE_POST,
}

PIPELINE_TASK_STAGE_MAP = {
    "tasks.download_audio": PIPELINE_STAGE_DOWNLOAD,
    "tasks.transcribe_audio": PIPELINE_STAGE_TRANSCRIBE,
    "tasks.diarize_and_align": PIPELINE_STAGE_DIARIZE,
    "tasks.cleanup_transcript": PIPELINE_STAGE_CLEANUP,
    "tasks.summarize_transcription": PIPELINE_STAGE_SUMMARIZE,
    "tasks.generate_embeddings": PIPELINE_STAGE_EMBED,
}

PIPELINE_STAGE_RANK = {PIPELINE_STAGE_QUEUED: 0}
PIPELINE_STAGE_RANK.update({stage: index for index, stage in enumerate(PIPELINE_STAGE_SEQUENCE, start=1)})


def get_queue_for_task(task_name: str) -> str:
    stage = PIPELINE_TASK_STAGE_MAP[task_name]
    return PIPELINE_STAGE_QUEUE_MAP[stage]
